name: ui_builder_c
description: Drag-and-drop UI builder with code panels

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
